name: Build APK with Attestation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK with attestation
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app.apk
        enable-attestation: true
